# Generated by Django 5.0.1 on 2024-01-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='subject',
        ),
        migrations.AddField(
            model_name='home',
            name='subject',
            field=models.ManyToManyField(blank=True, to='main.subject'),
        ),
    ]
