# Generated by Django 5.0.1 on 2024-01-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subject_remove_home_subject_home_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='subject',
            field=models.ManyToManyField(to='main.subject'),
        ),
    ]
