# Generated by Django 5.0.1 on 2024-01-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_awards_category_counter_education_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
