# Generated by Django 5.0.1 on 2024-01-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_project_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/services')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Awards',
            new_name='Award',
        ),
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
