# Generated by Django 5.0.1 on 2024-01-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_service_rename_awards_award_rename_partners_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TopSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('percent', models.IntegerField()),
                ('last_week', models.IntegerField()),
                ('last_month', models.IntegerField()),
            ],
        ),
    ]
