# Generated by Django 5.0.1 on 2024-01-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_project_category_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
