# Generated by Django 5.0.1 on 2024-01-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_link',
        ),
    ]
