# Generated by Django 5.0.1 on 2024-02-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_project_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='CV',
            field=models.FileField(blank=True, null=True, upload_to='media/about'),
        ),
    ]
